config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'static_pages/aboutUs'
  get 'static_pages/blushington'
  get 'static_pages/alibi'
  get 'static_pages/mac'

  resources :posts, only: [:show]

  resources :professionals, only: [:new, :show]

  resources :salons, only: [:new, :show]

  resources :users do
    resources :posts, shallow: true
    resources :likes, shallow: true
  end

  resources :sessions, only: [:new, :create, :destroy]

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @posts = Posts.all
    posts = Posts.all
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/aboutUs.html.erb
<div class="container">
  <h3>about us</h3>

  <p class="flow-text">We provide 24/7 access to top beauty professionals, products, salons and spas through a community of people that capture, review and share their experiences of products and services provided. We aim to connect you with the best of the beauty industry.</p>
</div>

app/views/static_pages/alibi.html.erb
<div class="container">
  <div class="row">
    <div class="col s12 m6 l6 ">
      <div style="margin-top: 20px;">ALIBI NYC SALON</div>
      <br>
      <div>PHONE NUMBER</div>
      <div>(212) 219-2806</div>
      <br>
      <div>LOCATION</div>
      <div>67 Greene St.</div>
      <div>Ste. 2</div>
      <div>New York NY 10012</div>
      <br>
      <div>MENU</div>
      <div class="row">
        <div class="col s12 m4 l4">
          <!-- <img src="http://i.imgur.com/RXRqYEeb.jpg"> -->
        </div>
        <div class="col s12 m4 l4">
          <!-- <img src="http://i.imgur.com/KN6Dp36b.jpg"> -->
        </div>
      </div>
      <div>WEBSITE</div>
      <div>http://www.alibinycsalon.com/</div>
    </div>
    <div class="col s12 m6 l6 center-align">
      <div class="row">
        <div style="margin-top: 20px;">PHOTOS</div>
        <div class="row">
          <div class="col s12 m4 l4 offset-m2 offset-l2">
            <img class="z-depth-2" src="https://i.imgur.com/1pSlRSIb.jpg">
          </div>
          <div class="col s12 m4 l4">
            <img class="z-depth-2" src="https://i.imgur.com/Tt2uNHub.jpg">
          </div>
        </div>
        <div class="row">
          <div class="col s12 m4 l4 offset-m2 offset-l2">
            <img class="z-depth-2" src="https://i.imgur.com/PnOxj0Qb.jpg">
          </div>
          <div class="col s12 m4 l4">
            <img class="z-depth-2" src="https://i.imgur.com/OftbK4bb.jpg">
          </div>
        </div>
      </div>
      <br>
      <div class="row">
        <div>REVIEWS</div>
        <div class="row center-align">
          <div class="col s12 m4 l4">
            <!-- <img src="http://i.imgur.com/tkh1qXEb.jpg"> -->
          </div>
          <div class="col s12 m12 l12 center-align">
            <img src="https://i.imgur.com/tkh1qXEb.jpg">
          </div>
          <div class="col s12 m4 l4">
            <!-- <img src="http://i.imgur.com/ipsh2eVb.jpg"> -->
          </div>
        </div>
        <div class="row">
          <a href="#" class="btn">SEE REVIEWS</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/blushington.html.erb
<div class="container">
  <div class="row">
    <div class="col s12 m6 l6 ">
      <div style="margin-top: 20px;">BLUSHINGTON MAKEUP & BEAUTY LOUNGE</div>
      <br>
      <div>PHONE NUMBER</div>
      <div>(646) 410-2208</div>
      <br>
      <div>LOCATION</div>
      <div>Le Parker Meridien</div>
      <div>119 West 56th Street</div>
      <div>New York NY 10019</div>
      <br>
      <div>MENU</div>
      <div class="row">
        <div class="col s12 m4 l4 responsive-img">
          <img class="z-depth-2" src="https://i.imgur.com/RXRqYEeb.jpg">
        </div>
        <div class="col s12 m4 l4 responsive-img">
          <img class="z-depth-2" src="https://i.imgur.com/KN6Dp36b.jpg">
        </div>
      </div>
      <div>WEBSITE</div>
      <div>http://www.blushington.com/</div>
    </div>
    <div class="col s12 m6 l6 center-align">
      <div class="row">
        <div style="margin-top: 20px;">PHOTOS</div>
        <div class="row">
          <div class="col s12 m4 l4 offset-m2 offset-l2">
            <img class="z-depth-2" style="margin: 2px;" src="http://i.imgur.com/ipsh2eVb.jpg">
          </div>
          <div class="col s12 m4 l4">
            <img class="z-depth-2" style="margin: 2px;" src="https://i.imgur.com/ipsh2eVb.jpg">
          </div>
        </div>
        <div class="row">
          <div class="col s12 m4 l4 offset-m2 offset-l2">
            <img class="z-depth-2" style="margin: 2px;" src="https://i.imgur.com/jUTnjItb.jpg">
          </div>
          <div class="col s12 m4 l4">
            <img class="z-depth-2" style="margin: 2px;" src="https://i.imgur.com/lHA1F5eb.jpg">
          </div>
        </div>
      </div>
      <br>
      <div class="row">
        <div>REVIEWS</div>
        <div class="row center-align">
          <div class="col s12 m4 l3">
            <img class="center-align" src="https://i.imgur.com/s2vtmCms.jpg">
          </div>
          <div class="col s12 m4 l3">
            <img class="center-align" src="https://i.imgur.com/333nLGfs.jpg">
          </div>
          <div class="col s12 m4 l3">
            <img class="center-align" src="https://i.imgur.com/EkreQAzs.jpg">
          </div>
        </div>
        <div class="row">
          <a href="#" class="btn">SEE REVIEWS</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<!-- <div class="poster"><img style="min-width: 100%; height: auto;" <img src="https://i.imgur.com/JZaPBd8.jpg" title="source: imgur.com" /></div> -->
<div class="poster"><img style="background-color: brown; min-width: 100%; height: auto;" <img src="http://i.imgur.com/V9UZYHI.png" title="source: imgur.com" /></div>

  <div class="container">
    <div style="margin-top: 20px;">FEATURED</div>
    <div class="row">
      <div class="col s12 m6 l6 center-align">
        <a href="<%= static_pages_blushington_path %>">
          <img class="responsive-img z-depth-2" style="margin: 5px; max-height:300px; width: auto;" src="https://i.imgur.com/ipsh2eV.jpg">
        </a>
      </div>
      <div class="col s12 m6 l6 center-align">
        <a href="<%= static_pages_blushington_path %>">
          <img class="responsive-img z-depth-2" style="margin: 5px; max-height:300px; width: auto;" src="https://i.imgur.com/tf3LRXw.jpg">
        </a>
      </div>
    </div>

    <div class="row">
      <div class="col s12 m6 l6 center-align">
        <a href="<%= static_pages_alibi_path %>">
          <img class="responsive-img z-depth-2" style="margin: 5px; max-height:300px; width: auto; max-width: 400px;" src="https://i.imgur.com/1pSlRSI.jpg">
        </a>
      </div>

        <div class="col s12 m6 l6 center-align">
          <a href="<%= static_pages_alibi_path %>">
            <img class="responsive-img z-depth-2" style="margin: 5px; max-height:300px; width: auto; max-width: 400px;" src="https://i.imgur.com/OftbK4b.jpg">
          </a>
        </div>
      </div>

      <div class="row">
        <div class="col s12 m6 l6 center-align">
          <a href="<%= static_pages_mac_path %>">
            <img class="responsive-img z-depth-2" style="margin: 5px; max-height:300px; width: auto; max-width: 400px;" src="https://i.imgur.com/HPMZc8W.jpg">
          </a>
        </div>

          <div class="col s12 m6 l6 center-align">
            <a href="<%= static_pages_mac_path %>">
              <img class="responsive-img z-depth-2" style="margin: 5px; max-height:300px; width: auto; max-width: 400px;" src="https://i.imgur.com/tkh1qXE.jpg">
            </a>
          </div>
        </div>
  </div>

app/views/static_pages/mac.html.erb
<div class="container">
  <div class="row">
    <div class="col s12 m6 l6 ">
      <div style="margin-top: 20px;">M.A.C.</div>
      <br>
      <div>PHONE NUMBER</div>
      <div>(212) 219-2806</div>
      <br>
      <div>LOCATION</div>
      <div>M·A·C PRO - NEW YORK CITY</div>
      <div>7 W. 22nd Street</div>
      <div>New York NY 10010</div>
      <br>
      <div>PRODUCTS</div>
      <div class="row">
        <div class="col s12 m4 l4">
          <img src="https://i.imgur.com/tXZLcVgs.jpg">
        </div>
        <p>Lady Danger</p>
        <p>$17</p>
        <p>Vivid bright coral-red (Matte)</p>
        <p>Formulated to shade, define and showcase the lips. Hundreds of hues, high-fashion textures. The iconic product that made M·A·C famous.</p>

        <div class="col s12 m4 l4">
          <img src="https://i.imgur.com/oKCBiXSs.jpg">
        </div>
        <p>Ruby Woo</p>
        <p>$17</p>
        <p>Very matte vivid blue-red (Retro Matte)</p>
        <p>Formulated to shade, define and showcase the lips. Hundreds of hues, high-fashion textures. The iconic product that made M·A·C famous.</p>

      </div>
      <div>WEBSITE</div>
      <div>http://www.alibinycsalon.com/</div>
    </div>
    <div class="col s12 m6 l6 center-align">
      <div class="row">
        <div style="margin-top: 20px;">PHOTOS</div>
        <div class="row">
          <div class="col s12 m4 l4 offset-m2 offset-l2">
            <img src="https://i.imgur.com/tXZLcVgb.jpg">
          </div>
          <div class="col s12 m4 l4">
            <img src="https://i.imgur.com/fGMZ19Yb.jpg">
          </div>
        </div>
        <div class="row">
          <div class="col s12 m4 l4 offset-m2 offset-l2">
            <img src="https://i.imgur.com/0MYd7tOb.jpg">
          </div>
          <div class="col s12 m4 l4">
            <img src="https://i.imgur.com/oKCBiXSb.jpgg">
          </div>
        </div>
      </div>
      <br>
      <div class="row">
        <div>REVIEWS</div>
        <div class="row center-align">
          <div class="col s12 m4 l4">
            <!-- <img src="http://i.imgur.com/tkh1qXEb.jpg"> -->
          </div>
          <div class="col s12 m12 l12 center-align">
            <img src="https://i.imgur.com/tkh1qXEb.jpg">
          </div>
          <div class="col s12 m4 l4">
            <!-- <img src="http://i.imgur.com/ipsh2eVb.jpg"> -->
          </div>
        </div>
        <div class="row">
          <a href="#" class="btn">SEE REVIEWS</a>
        </div>
      </div>
    </div>
  </div>
</div>