config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'static_pages/aboutUs'
  get 'static_pages/blushington'
  get 'static_pages/alibi'
  get 'static_pages/mac'

  resources :posts, only: [:show]

  resources :professionals, only: [:new, :show]

  resources :salons, only: [:new, :show]

  resources :users do
    resources :posts, shallow: true
    resources :likes, shallow: true
  end

  resources :sessions, only: [:new, :create, :destroy]

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :posts
  has_many :likes

  has_many :liked_salons, through: :likes, source: :salon
  has_many :liked_professionals, through: :likes, source: :professional
  has_many :liked_posts, through: :likes, source: :posts

  has_attached_file :profile_photo, styles: {
        thumb: '100x100>',
        square: '200x200#',
        medium: '300x300>'
        },
      url: ":s3_domain_url",
      path: "users/:id/profile_photo/:style_:basename.:extension"

    validates_attachment_content_type :profile_photo, :content_type => /\Aimage\/.*\Z/
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :grab_user, only: [:edit, :show, :update]
  before_action :grab_current_user

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user
    else
      redirect_to new_user_path
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :username, :profile_photo)
  end

  def grab_user
    @user = User.find(params[:id])
  end

  def grab_current_user
    @current_user = current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<h1>TESTING OUT THE INDEX PAGE</h1>

<% @users.each do |user| %>
  <%= user.email %>
<% end %>

app/views/users/new.html.erb
<div class="container">
  <h3>sign up</h3>

  <form action="<%= users_path %>" method="post" enctype="multipart/form-data" accept-charset="UTF-8" >
    <input  type="hidden"
          name="authenticity_token"
          value="<%= form_authenticity_token %>">

        <input type="text" name="user[username]" placeholder="username">

        <div id="fileUpload" class="file-field input-field row">
          <div id="fileUpload2" class="btn">
            <span>Add a profile photo</span>
            <input type="file" name="user[profile_photo]" id="profile_photo"/>
          </div>
        </div>

        <input type="text" name="user[email]" placeholder="email">
        <input type="password" name="user[password]" placeholder="password">




    <!-- <div><%= @user.profile_photo.url(:thumb) %></div> -->


    <input class="btn" type="submit">
  </form>
</div>

app/views/users/show.html.erb
<% user = @user %>

<div class="container">
  <div class="row">
     <div class="col s12">
        <h3 class="center-align"><%= @user.username %></h3>
      </div>
      <div class="col s12 center-align">
        <img class="circle responsive-img" <%= image_tag @user.profile_photo.url(:square) %>
      </div>
      <div class="col s12 center-align">
        <a class="btn center-align" href="<%= new_user_post_path(user.id) %>">Make a review</a>
      </div>
    </div>
</div>