config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'static_pages/aboutUs'
  get 'static_pages/blushington'
  get 'static_pages/alibi'
  get 'static_pages/mac'

  resources :posts, only: [:show]

  resources :professionals, only: [:new, :show]

  resources :salons, only: [:new, :show]

  resources :users do
    resources :posts, shallow: true
    resources :likes, shallow: true
  end

  resources :sessions, only: [:new, :create, :destroy]

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/posts.rb
class Posts < ActiveRecord::Base
  belongs_to :user
  belongs_to :salon
  belongs_to :professional
  has_many :likes

  has_many :posted_photos, through: :posts, source: :user
  
  has_attached_file :before_photo_id, styles: {
        thumb: '100x100>',
        square: '200x200#',
        medium: '300x300>'
        },
      url: ":s3_domain_url",
      path: "users/:id/before_photo_id/:style_:basename.:extension"

    validates_attachment_content_type :before_photo_id, :content_type => /\Aimage\/.*\Z/

    has_attached_file :after_photo_id, styles: {
          thumb: '100x100>',
          square: '200x200#',
          medium: '300x300>'
          },
        url: ":s3_domain_url",
        path: "users/:id/after_photo_id/:style_:basename.:extension"

      validates_attachment_content_type :after_photo_id, :content_type => /\Aimage\/.*\Z/
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :redirect_unless_logged_in
  before_action :grab_current_user

  def index
    @posts = Posts.find(params[:user_id])
    @user = User.find(params[:user_id])
    @allposts = Posts.all
  end

  def new
    @user = User.find(params[:user_id])
    @posts = Posts.new
  end

  def create
    @posts = Posts.new(posts_params)

    if @posts.save
      redirect_to user_posts_path
    else
      redirect_to user_posts_path
    end
  end

  def show
    @posts = Posts.all
  end

  def edit
    @posts = Posts.find(:user_id)
    @allposts = Posts.all
  end

  def update
    @posts = Posts.find(params[:id])
    @posts.update(posts_params)
    @posts.save
    render 'posts/index'
  end

  def destroy
    @post = Posts.find(params[:id])
    @post.destroy
    redirect_to new_user_path, :notice => "Your post has been deleted."
  end

  private

  def posts_params
    params.require(:posts).permit(:before_photo_id, :after_photo_id, :comment)
  end


  def redirect_unless_logged_in
    if session[:current_user_id]
      @current_user = current_user
    else
      redirect_to new_session_path unless @current_user
    end
  end

  def grab_current_user
    @current_user = current_user
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class="container">
  <h1>Edit your reviews</h1>

  <form action="<%= edit_post_path %>" method="post" enctype="multipart/form-data" accept-charset="UTF-8" >
    <input  type="hidden"
            name="authenticity_token"
            value="<%= form_authenticity_token %>">
    <input  type="hidden" name="_method" value="patch">
    <% if !@posts.before_photo_id? %>
      <h2>You don't have any reviews.<h2>
      <a href="<%= new_user_post_path(user.id) %>">Post a review</a>
    <% else %>
      <% @allposts.each do |p| %>
        <%= image_tag p.before_photo_id.url(:thumb) %>
        <%= link_to "Delete", @posts, :confirm => "Are you sure?", :method => :delete %>
        <%= image_tag p.after_photo_id.url(:thumb) %>
        <br>
        <p><%= p.comment %></p>
        <a href="<%= user_posts_path(:user_id) %>">Delete this review</a>
      <% end %>
    <% end %>

    <div id="fileUpload" class="file-field input-field row">
      <input class="file-path validate" type="text"/>
      <div id="fileUpload2" class=" teal lighten-4 btn">
        <span>Upload a before picture</span>
        <input type="file" name="posts[before_photo_id]" id="before_photo_id"/>
      </div>
    </div>

    <div id="fileUpload" class="file-field input-field row">
      <input class="file-path validate" type="text"/>
      <div id="fileUpload2" class=" teal lighten-4 btn">
        <span>Upload a after picture</span>
        <input type="file" name="posts[after_photo_id]" id="after_photo_id"/>
      </div>
    </div>

    <input type="text" name="posts[comment]" placeholder="Comments">

    <button class=" teal lighten-4 btn"
            type="submit"
            name="action">FINISHED
    </button>
    <br /><br />

    </fieldset>
</div>å

app/views/posts/index.html.erb
<% user = @user %>
<div class="container">
  <h3>reviews for <%= @user.username %></h3>
  <% if !@posts.before_photo_id? %>
    <div>You don't have any reviews.<div>
    <a href="<%= new_user_post_path(user.id) %>" class="teal lighten-4 btn">Post a review</a>
  <% else %>
      <% @allposts.each do |p| %>
      <div class="row">
        <div class="col s12 m6 l6 center-align">
          <%= image_tag p.before_photo_id.url(:square) %>
        </div>
        <div class="col s12 m6 l6 center-align">
          <%= image_tag p.after_photo_id.url(:square) %>
        </div>
      </div>

  <div class="row">
    <div class="col s12 m12">
      <div class="card-panel white">
        <span class="black-text"><%= p.comment %></span>
      </div>
    </div>
  </div>
    <% end %>
    <a href="<%= new_user_post_path(user.id) %>" class="btn">Post another review</a>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="container">
  <h3>make a review</h3>

  <fieldset>

    <form action="<%= user_posts_path %>" method="post" enctype="multipart/form-data" accept-charset="UTF-8" >
      <input  type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>">

      <div class="row">

        <div class="col s12 m6 l6">
          <div id="fileUpload" class="file-field input-field row">
            <div id="fileUpload2" class="btn">
              <span>Upload a before picture</span>
              <input type="file" name="posts[before_photo_id]" id="before_photo_id"/>
            </div>
          </div>
        </div>

        <div class="col s12 m6 l6">
          <div id="fileUpload" class="file-field input-field row">
            <!-- <input class="file-path validate" type="text"/> -->
            <div id="fileUpload2" class="btn">
              <span>Upload an after picture</span>
              <input type="file" name="posts[after_photo_id]" id="after_photo_id"/>
            </div>
          </div>
        </div>

      </div>

      <input type="text" name="posts[comment]" placeholder="Leave a review">

      <button class="btn waves-effect waves-light"
      type="submit"
      name="action">FINISHED
    </button>
    <br /><br />

  </fieldset>
</div>